force-app/main/default/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Total_Salary__c</fullName>
        <label>Total Salary</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Employees</relationshipLabel>
        <relationshipName>Employees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Salary__c</fullName>
        <description>Salary of an employee</description>
        <label>Salary</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/UpdTotalSalaryTest.cls
@isTest
public class UpdTotalSalaryTest {
    @isTest
    private static void method1(){
        Account acc1 = new Account(Name = 'Test1' , Total_Salary__c = 0);
        insert acc1;
        system.debug('***acc1 '+acc1);
        Employee__c emp1 = new Employee__c();
        emp1.Salary__c = 200.00;
        emp1.Account__c = acc1.Id;
        insert emp1;
        UpdTotalSalary u = new UpdTotalSalary ();
        Test.startTest();
        u.updateAccountTS(); 
        Test.stopTest();
        system.debug('***acc1 '+acc1);
        Account acc2 = [SELECT id , Total_Salary__c FROM Account where id =: acc1.id LIMIT 1 ];
        system.debug('***acc2 '+acc2);
        System.assertEquals(emp1.Salary__c,acc2.Total_Salary__c);
    }

}