force-app/main/default/objects/Client__c.object
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>P-{000}</displayFormat>
        <label>Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/accountController.cls
public class accountController {
 List<client__c> clie = [select Name from client__c];
    List<contact__c> cont = [select Name from contact__c];
 List<Project__c> proj = [select Name from Project__c];
    
    public List<client__c> getclie(){
        return clie;
    }
    
    public List<contact__c> getcont(){
        return cont;
    }
    
    public List<project__c> getproj(){
        return proj;
    }
}